services:
  - type: web
    name: tip-calculator
    env: node
    plan: free
    rootDir: tip-calculator
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NPM_VERSION
        value: 10.x
      - key: MONGODB_URI
        sync: false 